const catchError = require('./catchError');

describe('catchError', () => {
    it.todo('[1] should catch a thrown error')

    // This code in Chai need modify to jest
    
    /* 
    it('should catch a thrown error', () => {
        let ex;
        try {
            catchError(() => {
                throw new Error();
            });
        }
        catch (_ex) {
            ex = _ex;
        }
        assert(!ex, "the error should have been caught");
    });
    */
});


